#image: python:2
image: centos:7

before_script:
  - echo ${USER}
  - yum install -y environment-modules
  - yum -y install epel-release
  - yum install -y python2-pip
  - yum install -y git
  - pip install vsc-base
  - pip install easybuild-framework 
  - pip install python-graph-core
  - pip install python-graph-dot
  - pip install git+https://bearadmin:LuJx-ZrG2Fprs7ony685@gitlab.bham.ac.uk/res-comp-team/bear-software/2018a/easybuild-easyblocks.git

test:
  script:
  - BEAR_LICENSE_SERVER=dummy.licence.server USER=bot EASYBUILD_MODULE_SYNTAX=Tcl EASYBUILD_MODULES_TOOL=EnvironmentModulesC python -O -m test.easyconfigs.suite
  
